"""migration_nomi

Revision ID: 51bc248a7ffe
Revises: e4f8c9a2b1d3
Create Date: 2025-12-07 13:58:58.526902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bc248a7ffe'
down_revision: Union[str, None] = 'e4f8c9a2b1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_settings_key', table_name='settings')
    op.drop_table('settings')
    op.add_column('users', sa.Column('blocked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked_at')
    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='settings_pkey')
    )
    op.create_index('ix_settings_key', 'settings', ['key'], unique=False)
    # ### end Alembic commands ###
