"""add_file_size_to_files

Revision ID: 52e4c2040518
Revises: 51bc248a7ffe
Create Date: 2025-12-07 14:16:42.097255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e4c2040518'
down_revision: Union[str, None] = '51bc248a7ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_settings_key', table_name='settings')
    op.drop_table('settings')
    op.add_column('files', sa.Column('file_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_size')
    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='settings_pkey')
    )
    op.create_index('ix_settings_key', 'settings', ['key'], unique=False)
    # ### end Alembic commands ###
