"""add_admin_permissions_to_users

Revision ID: bc95e2ae559b
Revises: cbedcebbaf34
Create Date: 2025-11-30 02:46:03.073085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc95e2ae559b'
down_revision: Union[str, None] = 'cbedcebbaf34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_permissions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_permissions')
    # ### end Alembic commands ###
