"""add_processed_file_id_to_files

Revision ID: cbedcebbaf34
Revises: dabf14471202
Create Date: 2025-11-29 00:57:50.640914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbedcebbaf34'
down_revision: Union[str, None] = 'dabf14471202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('processed_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'processed_file_id')
    # ### end Alembic commands ###
